<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <!--
        # Собрать всё в правильном порядке
        .\mvnw install

        # Запустить demo-rest - контракт соберётся автоматически
        .\mvnw spring-boot:run -pl demo-rest -am
        # .\mvnw.cmd org.springframework.boot:spring-boot-maven-plugin:run -pl demo-rest

        # Собрать только контракт (если менял только его)
        .\mvnw install -pl books-api-contract
    -->

    <groupId>edu.rutmiit.demo</groupId>
    <artifactId>demo-rest-root</artifactId>
    <version>1.0</version>
    <packaging>pom</packaging>
    <name>demo-rest [root aggregator]</name>

    <modules>
        <module>bank-api-contract</module>
        <module>demo-rest</module>
        <module>bank-events-contract</module>
        <module>audit-service</module>
        <module>grpc-analytics-server</module>
        <module>bank-grpc-contract</module>
        <module>grpc-enrichment-client</module>
        <module>notification-service</module>
        <module>01-persistence-and-data-ownership/bank-service</module>
    </modules>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-autoconfigure</artifactId>
            <version>4.1.0</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
            <version>4.1.0</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>jakarta.validation</groupId>
            <artifactId>jakarta.validation-api</artifactId>
            <version>3.1.1</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <version>4.1.0</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>21</source>
                    <target>21</target>
                    <compilerArgs>--enable-preview</compilerArgs>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
