syntax = "proto3";
option java_package = "edu.rutmiit.demo.grpc";
option java_multiple_files = true;
package bankanalytic;

service BankAnalytics {

    rpc EvaluateLoan (LoanScoringRequest) returns (LoanScoringResponse);
}

// Запрос на анализ соответствие кредитным условиям человека
message LoanScoringRequest {
    int64         application_id              = 1;
    int64         client_id           = 2;  // ID клиента
    double        requested_amount      = 3;  // запрашиваемая сумма
    double        monthly_income    = 4;  // доход
    double        current_debt            = 5;  // нынешний долг
}

// Ответ с результатами системы оценки
message LoanScoringResponse {
    int64  application_id                    = 1;
    int64  client_id                   = 2;  // ID кандидата
    bool is_approved                  = 3;  // true - одобрен, false - отказ
    double interest_rate         = 4;  // процентная ставка
    double debt_load_ratio      = 5;  // процент долговой нагрузки
    string rejection_reason            = 6;  // причина отказа
    string recommendation       =7; // "AUTO_APPROVE" "REJECT"
}