ALTER TABLE books
    ADD COLUMN created_at TIMESTAMP WITH TIME ZONE NULL;

ALTER TABLE books
    ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;

UPDATE books
SET created_at = CURRENT_TIMESTAMP
WHERE created_at IS NULL;

ALTER TABLE books
    ALTER COLUMN created_at SET NOT NULL;

